# Generated by Django 2.1.5 on 2019-01-11 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='building',
        ),
    ]
