# Generated by Django 2.1.2 on 2019-01-13 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='cityevent',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.City'),
        ),
        migrations.AddField(
            model_name='cityevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
        migrations.AddField(
            model_name='buildingevent',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Building'),
        ),
        migrations.AddField(
            model_name='buildingevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
        migrations.AddField(
            model_name='building',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildingCity', to='event.City'),
        ),
        migrations.AddField(
            model_name='block',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Salon'),
        ),
        migrations.AddField(
            model_name='actorevent',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Actor'),
        ),
        migrations.AddField(
            model_name='actorevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
    ]
