# Generated by Django 2.1.2 on 2019-01-12 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='actor',
            name='event',
        ),
        migrations.RemoveField(
            model_name='cityevent',
            name='building',
        ),
        migrations.RemoveField(
            model_name='cityevent',
            name='salon',
        ),
        migrations.AddField(
            model_name='actorevent',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Actor'),
        ),
        migrations.AddField(
            model_name='actorevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
    ]
