# Generated by Django 2.1.5 on 2019-01-13 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0002_auto_20190113_2202'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=200)),
                ('money', models.FloatField()),
                ('credit_card_numer', models.CharField(max_length=200)),
                ('user_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='userpastevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='onlyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
