# Generated by Django 2.1.5 on 2019-01-13 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190113_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlyuser',
            old_name='credit_card_numer',
            new_name='credit_card_number',
        ),
    ]
