<<<<<<< HEAD
# Generated by Django 2.1.2 on 2019-01-12 21:32
=======
# Generated by Django 2.1.5 on 2019-01-12 22:31
>>>>>>> event

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ticket_price', models.FloatField()),
                ('ticket_count', models.IntegerField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Block')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Salon')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Seat')),
            ],
        ),
    ]
