# Generated by Django 2.1.5 on 2019-01-14 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='block',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='event.Block'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='salon',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='event.Salon'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Seat'),
        ),
    ]
